### ISSUE TITLE
Popups on schedules map

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/omeka-s-theme#52]
Should they receive any special styles?

**Comment by lmullen** [comment]
- [ ] Jim will make the links from the map popups open a new tab
- [ ] Kim will look at the styles for the popups/labels

**Comment by kimisgold** [comment]
I think these might fall within @jimsafley's purview. He has a better understanding of how these popups are populated, and he probably knows where to change the leaflet option for the default popup width.

**Comment by kimisgold** [comment]
The popups are now fixed to be 400px in width and show the first 10 schedule results.

**Comment by IdaAkiwumi** [comment]
@kimisgold Is it possible for the full popups to display within the viewable area (as much as possible) and not necessarily above the selected city? This is what happens when I select Weld, Colorado. I have to keep pressing zoom out to see the full box. So maybe the arrow can be to the side or below the selected city and the box itself can adjust based on the rotation of the arrow?

<img width="1166" alt="Screen Shot 2020-12-10 at 3 16 20 PM" src="https://user-images.githubusercontent.com/618307/101824989-029d5600-3afb-11eb-9255-17aa6f30db36.png">

**Comment by kimisgold** [comment]
I think this is starting to get beyond the initial scope of the issue, which primarily concerns the styling for the popups. I'll open an issue on https://github.com/religious-ecologies/Mare-module since that handles the map functionality.

@lmullen Do the latest changes resolve the issue?

**Comment by lmullen** [comment]
I agree that there is more we can do to improve style and functionality of this map. But for now, we just wanted to have a good, workable first version. I like @kimisgold's idea of calling this done for now, and opening an issue on the Mare-module repo to gather remaining ideas.
