### ISSUE TITLE
Ordering of item sets and schedules

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/omeka-s-theme#53]
The default ordering throughout seems to be data created in descending order. I'm not sure that is meaningful to the user. Is there a different default that we can use?

**Comment by lmullen** [comment]
Need to play around to see if we can find a more natural order to use by default.

**Comment by lmullen** [comment]
@kimisgold For the browse page, would it be possible to restrict the items displayed to just those in the schedules item set? Right now I think it is drawing from all itemsets, but I don't think we anticipated using it for anything other than schedules. Is that right? 

If it can be restricted to just schedules, then displaying them in created ascending order might be the easiest solution to the original issue here.

**Comment by kimisgold** [comment]
I've updated the navigation to use the schedules resource template id since I was already using it elsewhere in the browse filters module. [I've also updated that module to also include that parameter when building queries](https://github.com/religious-ecologies/mare-browse-filters/commit/5446633a28050b407161b23f9b3db3877a1cccc4).

**Comment by kimisgold** [comment]
Schedules should now sort by created ascending order, applied in the Omeka navigation admin and [the browse filter module](https://github.com/religious-ecologies/mare-browse-filters/commit/424bcc7d827675e0991acff0190226b136b7fb7c).

**Comment by lmullen** [comment]
LGTM! 🚀 

Perhaps some other time we will find a better sort order, but this certainly works for now.
